/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.mycompany.interfaces;

import com.mycompany.controls.ControlRegProd;
import java.awt.Color;
import java.io.File;
import static java.lang.Integer.parseInt;
import java.time.LocalDate;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;

/**
 *
 * @author luisr
 */
public class InterfazDelProduct extends javax.swing.JPanel implements java.beans.Customizer {
    ControlRegProd regProduct = new ControlRegProd();
    
    public InterfazDelProduct(ControlRegProd controlProd) {
        this.regProduct = controlProd;
        initComponents();
        if (searchPanel.isVisible()){
            dataPanel.setVisible(false);
        }
        
    }
    

    
    private Object bean;

    /**
     * Creates new customizer InterfazDeleteProduct
     */
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataPanel = new javax.swing.JPanel();
        header = new javax.swing.JLabel();
        instructions = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        codeField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        promoField = new javax.swing.JTextField();
        date1Field = new javax.swing.JTextField();
        date2Field = new javax.swing.JTextField();
        imgField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        descText = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        headAche = new javax.swing.JCheckBox();
        jointAche = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        allergi1 = new javax.swing.JCheckBox();
        allergi2 = new javax.swing.JCheckBox();
        fileChoose = new javax.swing.JButton();
        imgView = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();
        containerPanel = new javax.swing.JPanel();
        searchPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        instructions2 = new javax.swing.JLabel();
        searchCodeField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        header.setText("jLabel2");

        instructions.setText("Mostrando informacion del producto que desea eliminar:");

        jLabel1.setText("Codigo del producto:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Descripcion:");

        jLabel4.setText("Precio:");

        jLabel5.setText("Precio de promocion:");

        jLabel6.setText("Fecha de inicio de la promocion:");

        jLabel7.setText("Fecha de fin de la promocion:");

        jLabel8.setText("Imagen del producto:");

        codeField.setEditable(false);
        codeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeFieldActionPerformed(evt);
            }
        });

        nameField.setEditable(false);
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });

        priceField.setEditable(false);
        priceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceFieldActionPerformed(evt);
            }
        });

        promoField.setEditable(false);

        date1Field.setEditable(false);
        date1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date1FieldActionPerformed(evt);
            }
        });

        date2Field.setEditable(false);
        date2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date2FieldActionPerformed(evt);
            }
        });

        imgField.setEditable(false);
        imgField.setFocusable(false);
        imgField.setVerifyInputWhenFocusTarget(false);
        imgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imgFieldActionPerformed(evt);
            }
        });

        descText.setEditable(false);
        descText.setColumns(20);
        descText.setRows(5);
        jScrollPane2.setViewportView(descText);

        jLabel9.setText("Tipo de malestares que alivia el producto:");

        headAche.setText("Dolor de cabeza");
        headAche.setEnabled(false);
        headAche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headAcheActionPerformed(evt);
            }
        });

        jointAche.setText("Dolor articular");
        jointAche.setEnabled(false);

        jLabel10.setText("Tipo de alergias que alivia el producto:");

        allergi1.setText("alergia1");
        allergi1.setEnabled(false);
        allergi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allergi1ActionPerformed(evt);
            }
        });

        allergi2.setText("alergia2");
        allergi2.setEnabled(false);

        fileChoose.setText("Elegir archivo");
        fileChoose.setEnabled(false);
        fileChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooseActionPerformed(evt);
            }
        });

        deleteButton.setText("Borrar");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2)
                                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date2Field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(date1Field, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(promoField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codeField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, dataPanelLayout.createSequentialGroup()
                                        .addComponent(imgField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(fileChoose))))
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgView, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(dataPanelLayout.createSequentialGroup()
                                        .addComponent(allergi1)
                                        .addGap(27, 27, 27)
                                        .addComponent(allergi2))))
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jointAche)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(headAche))))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(instructions)
                        .addGap(0, 398, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(1325, 1325, 1325))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructions)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(codeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(allergi1)
                    .addComponent(allergi2))
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(dataPanelLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jointAche)
                                    .addComponent(headAche)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(promoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(date1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(date2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(imgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fileChoose))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(imgView, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(393, Short.MAX_VALUE))
        );

        add(dataPanel, java.awt.BorderLayout.CENTER);

        searchPanel.setToolTipText("");
        searchPanel.setAutoscrolls(true);
        searchPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setText("Codigo:");
        searchPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 93, -1, -1));

        instructions2.setText("Ingrese el  codigo del producto a eliminar:");
        searchPanel.add(instructions2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 230, -1));

        searchCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchCodeFieldActionPerformed(evt);
            }
        });
        searchPanel.add(searchCodeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 90, 250, -1));

        searchButton.setText("Buscar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchPanel.add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 140, -1, -1));

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        searchPanel.getAccessibleContext().setAccessibleParent(this);

        add(containerPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        int index = regProduct.searchCode(searchCodeField.getText());
        if ( index >= 0){
            dataPanel.setVisible(true);
            searchPanel.setVisible(false);
            JOptionPane.showMessageDialog(null, "Producto encontrado.");
            fillFields(index);
        }else{
            JOptionPane.showMessageDialog(null, "Producto no encontrado.");
            searchCodeField.setText("");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchCodeFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_searchCodeFieldActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        int index = regProduct.deleteCode(searchCodeField.getText());
        if ( index >= 0){
            dataPanel.setVisible(false);
            searchPanel.setVisible(true);
            JOptionPane.showMessageDialog(null, "Producto eliminado.");
            searchCodeField.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Producto no encontrado.");
            searchCodeField.setText("");
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void fileChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooseActionPerformed
        // Se debe agregar un file chooser:
        JFileChooser fc = new JFileChooser();
        if (evt.getSource() == fileChoose) {
            int returnVal = fc.showOpenDialog(fc);
            if (returnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                String path = file.getAbsolutePath();
                // use the path here
                imgField.setText(path);
                //actualizamos el visualizador de imagenes
                ImageIcon icon = new ImageIcon(path);
                imgView.setIcon(icon);
            }
        }
    }//GEN-LAST:event_fileChooseActionPerformed

    private void allergi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allergi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_allergi1ActionPerformed

    private void headAcheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headAcheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headAcheActionPerformed

    private void imgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imgFieldActionPerformed

    private void date2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date2FieldActionPerformed

    private void date1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date1FieldActionPerformed

    private void priceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceFieldActionPerformed

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void codeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeFieldActionPerformed
    private void resetFields(){
        
        codeField.setText("");
        nameField.setText("");
        priceField.setText("");
        descText.setText("");
        promoField.setText("");
        imgField.setText("");
        date1Field.setText("");
        date2Field.setText("");
        
        headAche.setSelected(false);
        jointAche.setSelected(false);
        allergi1.setSelected(false);
        allergi2.setSelected(false);
        
        imgView.setIcon(null);
        
    }
    
    private boolean checkFields(){
        int count = 0;
        if (codeField.getText().trim().isEmpty()){
            codeField.setBorder(new LineBorder(Color.RED, 2));
            count++;
        } else {
            codeField.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (nameField.getText().trim().isEmpty()){
            nameField.setBorder(new LineBorder(Color.RED, 2));
            count++;
        }else {
            nameField.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (descText.getText().trim().isEmpty()){
            jScrollPane2.setBorder(new LineBorder(Color.RED, 2));;
        }else {
            jScrollPane2.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("jScrollPane.border"));
        }
        if (priceField.getText().trim().isEmpty()){
            priceField.setBorder(new LineBorder(Color.RED, 2));
            count++;
        }else {
            priceField.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (promoField.getText().trim().isEmpty()){
            promoField.setBorder(new LineBorder(Color.RED, 2));
            count++;
        }else {
            promoField.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (imgField.getText().trim().isEmpty()){
            imgField.setBorder(new LineBorder(Color.RED, 2));
            count++;
        }else {
            imgField.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (date1Field.getText().trim().isEmpty()){
            date1Field.setBorder(new LineBorder(Color.RED, 2));
            count++;
        }else {
            date1Field.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (date2Field.getText().trim().isEmpty()){
            date2Field.setBorder(new LineBorder(Color.RED, 2));
            count++;
        }else {
            date2Field.setBorder(UIManager.getLookAndFeel().getDefaults().getBorder("TextField.border"));
        }
        if (count > 0){
            return (false);
        }
        return (true);
    }
    
    public void resetStiles (){
        
    }
    
    public void fillFields (int index){
        String bene = new String();
        codeField.setText(regProduct.getCode(index));
        nameField.setText(regProduct.getNombre(index));
        priceField.setText(regProduct.getPrice(index));
        descText.setText(regProduct.getDesc(index));
        promoField.setText(regProduct.getPricePromo(index));
        imgField.setText(regProduct.getImg(index));
        date1Field.setText(regProduct.getDate1(index));
        date2Field.setText(regProduct.getDate2(index));
        
        bene = "Dolor de cabeza";
        if(regProduct.getBene(index).contains(bene)){
            headAche.setSelected(true);
        }
        bene = "Dolor articular.";
        if(regProduct.getBene(index).contains(bene)){
            headAche.setSelected(true);
        }
        bene = "Alergia 1";
        if(regProduct.getBene(index).contains(bene)){
            allergi1.setSelected(true);
        }
        bene = "Alergia 2";
        if(regProduct.getBene(index).contains(bene)){
            allergi2.setSelected(true);
        }
                
        ImageIcon icon = new ImageIcon(regProduct.getImg(index));
        imgView.setIcon(icon);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allergi1;
    private javax.swing.JCheckBox allergi2;
    private javax.swing.JTextField codeField;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JTextField date1Field;
    private javax.swing.JTextField date2Field;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextArea descText;
    private javax.swing.JButton fileChoose;
    private javax.swing.JCheckBox headAche;
    private javax.swing.JLabel header;
    private javax.swing.JTextField imgField;
    private javax.swing.JLabel imgView;
    private javax.swing.JLabel instructions;
    private javax.swing.JLabel instructions2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JCheckBox jointAche;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField promoField;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchCodeField;
    private javax.swing.JPanel searchPanel;
    // End of variables declaration//GEN-END:variables
}
